### PR TITLE
Using rejection sampling to avoid invalid salts for md5crypt (#1)

### LINKED ISSUE #1: md5crypt Generate salts containing $ break Validate
It appears that the random salt generation can cause Validate to not work properly because it could contain a `$` character that is then used as a separator between the salt and the hash.

See also: https://github.com/gopasspw/gopass/pull/2117 and https://github.com/gopasspw/gopass/issues/2121

To test this:

https://go.dev/play/p/tr4BKz0sHh0

As you can see all errors are coming from `$` in the salt.

### PR DESCRIPTION
**Pull request by AnomalRoil**
This fixes #1 

* Using rejection sampling to avoid invalid salts for md5crypt
* Adding many passes tests to all schemes and patching the existing tests
* Adding CI tests
* Adding go mod

### CODE REVIEW

File: ssha256/ssha256_test.go [hunk 1]
```diff
@@ -35,7 +35,7 @@ func TestGenerate4(t *testing.T) {
 		return
 	}
 
-	if res, err = ssha256.Validate(pass, hash); err != nil && res != false {
+	if res, err = ssha256.Validate(pass, hash); err != nil || res != true {
```
Comment (jsimonetti) [inline ssha256/ssha256_test.go:38]: What exactly is the reason for this inverse logic? Was that a result of debugging you did while finding the fix?

File: ssha256/ssha256_test.go [hunk 2]
```diff
@@ -51,7 +51,32 @@ func TestGenerate8(t *testing.T) {
...
```
Comment (jsimonetti) [inline ssha256/ssha256_test.go:54]: Same as above.

File: ssha512/ssha512_test.go [hunk 3]
```diff
@@ -35,7 +35,7 @@ func TestGenerate4(t *testing.T) {
 		return
 	}
 
-	if res, err = ssha512.Validate(pass, hash); err != nil && res != false {
+	if res, err = ssha512.Validate(pass, hash); err != nil || res != true {
```
Comment (jsimonetti) [inline ssha512/ssha512_test.go:38]: Same as above

File: ssha512/ssha512_test.go [hunk 4]
```diff
@@ -51,7 +51,32 @@ func TestGenerate8(t *testing.T) {
...
```
Comment (jsimonetti) [inline ssha512/ssha512_test.go:54]: Same as above

**Review by jsimonetti — COMMENTED** [review]
I haven't encountered this issue yet, but I appreciate the fix!
Could you have a look at the logic comment before I merge this?

Thank you for your effort sofar!

File: ssha256/ssha256_test.go (hunk 1 above)
Comment (jsimonetti) [reply ssha256/ssha256_test.go:38]: Hah, nevermind :) I found the answer myself. It turned out I had an inconsistency in the testing between different hash algorithms.

**Comment by jsimonetti** [comment]
This looks good to me. Thanks again for the fix. Closes #2

File: ssha256/ssha256_test.go (hunk 1 above)
Comment (AnomalRoil) [reply ssha256/ssha256_test.go:38]: Yup, it was just a correction because it seemed like it was a copy-paste from the "invalid test" rather than the "valid test" and we're expecting a `true`, so we want to report a `false` or an `err` and not both an `err` and a `true`.
